// <auto-generated />
using System;
using AMH_MarketPlace.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMH_MarketPlace.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230223124311_updateTableTransaction")]
    partial class updateTableTransaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMH_MarketPlace.Entities.Bank.Wallet.UserWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("birth_date");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("city");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<string>("NIK")
                        .HasColumnType("Varchar(16)")
                        .HasColumnName("nik");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("National")
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("national");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("NIK")
                        .IsUnique()
                        .HasFilter("[nik] IS NOT NULL");

                    b.HasIndex("WalletId");

                    b.ToTable("m_user_wallet");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Bank.Wallet.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint")
                        .HasColumnName("balance");

                    b.Property<string>("NoWallet")
                        .IsRequired()
                        .HasColumnType("Varchar(17)")
                        .HasColumnName("no_wallet");

                    b.HasKey("Id");

                    b.ToTable("m_wallet");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Store.Product.CategoryProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("m_category_product");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Store.Product.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_product_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(150)")
                        .HasColumnName("name");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<float?>("SizeCm")
                        .HasColumnType("real")
                        .HasColumnName("size_cm");

                    b.Property<float?>("SizeInch")
                        .HasColumnType("real")
                        .HasColumnName("size_inch");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("store_id");

                    b.Property<float?>("WeightG")
                        .HasColumnType("real")
                        .HasColumnName("weight_g");

                    b.Property<float?>("WeightKg")
                        .HasColumnType("real")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("m_product");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Store.Product.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ContenType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("conten_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.ToTable("m_product_image");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Store.RateStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Rate1")
                        .HasColumnType("int")
                        .HasColumnName("rate1");

                    b.Property<int>("Rate2")
                        .HasColumnType("int")
                        .HasColumnName("rate2");

                    b.Property<int>("Rate3")
                        .HasColumnType("int")
                        .HasColumnName("rate3");

                    b.Property<int>("Rate4")
                        .HasColumnType("int")
                        .HasColumnName("rate4");

                    b.Property<int>("Rate5")
                        .HasColumnType("int")
                        .HasColumnName("rate5");

                    b.HasKey("Id");

                    b.ToTable("m_rate_store");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Store.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("RateStoreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rate_store_id");

                    b.Property<Guid>("StoreImageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("store_image_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RateStoreId");

                    b.HasIndex("StoreImageId");

                    b.ToTable("m_store");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Store.StoreImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ContenType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("conten_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.HasKey("Id");

                    b.ToTable("m_store_image");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Transaction.TransacPurchase.PurchaseProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.ToTable("m_purchase_product");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Transaction.TransacWallet.TopUpWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("Varchar(10)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transaction_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("m_topup_wallet");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Transaction.TransacWallet.TransferWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<string>("NoWalletTarget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("no_wallet_target");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("Varchar(10)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transaction_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("m_transfer_wallet");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Transaction.TransacWallet.WithdrawalWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("Varchar(10)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transaction_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wallet_id");

                    b.Property<Guid>("bankId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bank_id");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("m_withdrawal_wallet");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Transaction.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("description");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("Varchar(20)")
                        .HasColumnName("payment_method");

                    b.Property<string>("ReferencePg")
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("reference_pg");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("Varchar(15)")
                        .HasColumnName("status");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("transaction_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("m_transaction");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.User.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("m_credential");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.User.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(10)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("m_role");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.User.SubUser.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address1")
                        .HasColumnType("Varchar(255)")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasColumnType("Varchar(255)")
                        .HasColumnName("address2");

                    b.Property<string>("City")
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("PostCode")
                        .HasColumnType("Varchar(5)")
                        .HasColumnName("post_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("m_address");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.User.SubUser.Notifications.CategoryNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(10)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("m_category_notif");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.User.SubUser.Notifications.NotifRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.HasKey("Id");

                    b.ToTable("m_notif_read");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.User.SubUser.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("CategoryNotificationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_notification_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("NotifReadId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("is_read_id");

                    b.Property<string>("Title")
                        .HasColumnType("Varchar(255)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryNotificationId");

                    b.HasIndex("NotifReadId");

                    b.ToTable("m_notif");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("credential_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("Varchar(13)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("m_user");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Bank.Wallet.UserWallet", b =>
                {
                    b.HasOne("AMH_MarketPlace.Entities.Bank.Wallet.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Store.Product.Product", b =>
                {
                    b.HasOne("AMH_MarketPlace.Entities.Store.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Store.Store", b =>
                {
                    b.HasOne("AMH_MarketPlace.Entities.Store.RateStore", "RateStore")
                        .WithMany()
                        .HasForeignKey("RateStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMH_MarketPlace.Entities.Store.StoreImage", "StoreImage")
                        .WithMany()
                        .HasForeignKey("StoreImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RateStore");

                    b.Navigation("StoreImage");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Transaction.TransacWallet.TopUpWallet", b =>
                {
                    b.HasOne("AMH_MarketPlace.Entities.Transaction.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMH_MarketPlace.Entities.Bank.Wallet.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Transaction.TransacWallet.TransferWallet", b =>
                {
                    b.HasOne("AMH_MarketPlace.Entities.Transaction.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMH_MarketPlace.Entities.Bank.Wallet.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Transaction.TransacWallet.WithdrawalWallet", b =>
                {
                    b.HasOne("AMH_MarketPlace.Entities.Transaction.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMH_MarketPlace.Entities.Bank.Wallet.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.Transaction.Transaction", b =>
                {
                    b.HasOne("AMH_MarketPlace.Entities.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.User.Credential", b =>
                {
                    b.HasOne("AMH_MarketPlace.Entities.User.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.User.SubUser.Address", b =>
                {
                    b.HasOne("AMH_MarketPlace.Entities.User.User", null)
                        .WithOne("Address")
                        .HasForeignKey("AMH_MarketPlace.Entities.User.SubUser.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.User.SubUser.Notifications.Notification", b =>
                {
                    b.HasOne("AMH_MarketPlace.Entities.User.SubUser.Notifications.CategoryNotification", "CategoryNotification")
                        .WithMany()
                        .HasForeignKey("CategoryNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMH_MarketPlace.Entities.User.SubUser.Notifications.NotifRead", "NotifRead")
                        .WithMany()
                        .HasForeignKey("NotifReadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryNotification");

                    b.Navigation("NotifRead");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.User.User", b =>
                {
                    b.HasOne("AMH_MarketPlace.Entities.User.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("AMH_MarketPlace.Entities.User.User", b =>
                {
                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
